from familienportal.admin_status_api import router as admin_status_api_router
from familienportal.admin_status_web import router as admin_status_web_router
from familienportal.extensions import BUILTIN_MODULES
from familienportal.genealogy_document_proxy import router as genealogy_document_proxy_router
from familienportal.genealogy_documents_web import router as genealogy_documents_router
from familienportal.genealogy_picker_web import router as genealogy_picker_router
from familienportal.genealogy_privacy_web import router as genealogy_privacy_router
from familienportal.gramps_api import router as gramps_api_router
from familienportal.gramps_extra_web import router as gramps_extra_router
from familienportal.gramps_person_web import router as gramps_person_router
from familienportal.gramps_transfer_web import router as gramps_transfer_router
from familienportal.gramps_web import router as gramps_router
from familienportal.integration_admin_web import router as integration_admin_router
from familienportal.main import app
from familienportal.paperless_web import router as paperless_router
from familienportal.role_mfa_policy import RoleMfaPolicyMiddleware
from familienportal.security_http import CsrfOriginMiddleware, SecurityHeadersMiddleware
from familienportal.tasks_web import router as tasks_router

BUILTIN_MODULES["genealogy"]["route"] = "/genealogy"

app.include_router(gramps_router)
app.include_router(gramps_extra_router)
app.include_router(gramps_api_router)
app.include_router(gramps_transfer_router)
app.include_router(gramps_person_router)
app.include_router(genealogy_documents_router)
app.include_router(genealogy_picker_router)
app.include_router(genealogy_document_proxy_router)
app.include_router(genealogy_privacy_router)
app.include_router(paperless_router)
app.include_router(integration_admin_router)
app.include_router(admin_status_web_router)
app.include_router(admin_status_api_router)
app.include_router(tasks_router)
app.add_middleware(SecurityHeadersMiddleware)
app.add_middleware(CsrfOriginMiddleware)
app.add_middleware(RoleMfaPolicyMiddleware)
