from familienportal.gramps_web import router as gramps_router
from familienportal.main import app
from familienportal.role_mfa_policy import RoleMfaPolicyMiddleware
from familienportal.security_http import CsrfOriginMiddleware, SecurityHeadersMiddleware

app.include_router(gramps_router)
app.add_middleware(SecurityHeadersMiddleware)
app.add_middleware(CsrfOriginMiddleware)
app.add_middleware(RoleMfaPolicyMiddleware)
